image: node:16

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  variables:
    npm_config_registry: https://registry.npmmirror.com
  script:
    - npm install
    - npm run config
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
  environment:
    name: production
    url: https://blog.longtian.info
  
