pages:
  image: node:16-alpine
  stage: build
  variables:
    npm_config_registry: https://registry.npmmirror.com
  script:
    - npm install
    - npm run config
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master

upload:
  image: ossutil
  stage: deploy
  script:
    - ossutil cp public oss://longtian-blog --recursive
  environment:
    name: production
    url: https://blog.longtian.info


