image: node:latest

cache:
  paths:
    - node_modules/

build:
  script:
    - npm install
    - npm run build 
    - ls
  artifacts:
    paths:
      - public

dep:
  image: registry.longtian.info/longtian/ossutil
  script:
    - ls
