language: node_js
node_js: stable

# S: Build Lifecycle
install:
- npm install

script:
- npm run generate

after_script:
- cd ./public
- git init
- git config user.name "Travis"
- git config user.email "wyvernnot@gmail.com"
- git add .
- git commit -m "Update docs"
- git branch -m gh-pages
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
# E: Build LifeCycle

branches:
  only:
  - master
env:
  global:
  - GH_REF: https://github.com/longtian/blogs.git
